Repository ripe-tech/ripe-commons-js, pull requests merged in 2021-06, with the labels that each got.

#13 feat: port functions from ripe-components-vue
  CHANGELOG.md
  js/config.js
  js/context.js
  js/filter.js
  js/index.js
  js/time.js
  js/util.js
  test/base/context.js
Labels: enhancement

#16 feat: barcode 128 set B encoding function
  CHANGELOG.md
  js/barcode.js
  js/index.js
  test/base/barcode.js
Labels: enhancement, unit-testing

#15 fix: change operator to $and if only a keyword is given as filter
  js/filter.js
Labels: bug, talk

#19 version: 0.4.1
  CHANGELOG.md
  package.json
Labels: enhancement

#18 docs: github templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/user_story.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#20 feat: improve encodeBarcode128B and warn about its limitations
  js/barcode.js
Labels: documentation, enhancement

#17 test: filterToParams unit tests
  js/filter.js
  js/util.js
  test/base/filter.js
  test/base/util.js
  types/filter.d.ts
  types/index.d.ts
  types/util.d.ts
Labels: unit-testing
