Repository ripe-tech/ripe-commons-js, pull requests merged in 2022-06, with the labels that each got.

#42 #17: Add semaphore util
  CHANGELOG.md
  js/index.js
  js/semaphore.js
  test/semaphore.js
Labels: enhancement, unit-testing

#43 version: 0.11.0
  CHANGELOG.md
  package.json
Labels: enhancement, release 🎉

#39 feat: add getRipeWhiteAdminOptions
  CHANGELOG.md
  js/env.js
  test/env.js
Labels: enhancement

#44 test: add tests for new env functions
  CHANGELOG.md
  test/env.js
Labels: enhancement, unit-testing

#46 #961 Add getRipeConfigOptions methods
  CHANGELOG.md
  js/env.js
  test/env.js
Labels: enhancement

#47 version: 0.12.0
  CHANGELOG.md
  package.json
Labels: enhancement, release 🎉
