Repository ripe-tech/ripe-commons-js, pull requests merged in 2022-02, with the labels that each got.

#30 feat: mime type util function
  CHANGELOG.md
  js/util.js
  test/util.js
Labels: enhancement, unit-testing

#31 fix: exact length limit break
  CHANGELOG.md
  js/string.js
  test/string.js
Labels: bug

#32 version: 0.8.1
  CHANGELOG.md
  package.json
Labels: release 🎉
